//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop_Samarin.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamarinR_BarbershopEntities1 : DbContext
    {
        public SamarinR_BarbershopEntities1()
            : base("name=SamarinR_BarbershopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admins> Admins { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Masters> Masters { get; set; }
        public DbSet<Records> Records { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
