//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop_Samarin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters
    {
        public Masters()
        {
            this.Clients = new HashSet<Clients>();
            this.Records = new HashSet<Records>();
        }
    
        public int ID { get; set; }
        public string Master_Name { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Records> Records { get; set; }
    }
}
